apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: polom-cl
spec:
  acme:
    email: shananatest@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: polom-key-secret  # ACME secret
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - kind: Gateway
                name: polom-gateway
                namespace: nginx-gateway

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: polom-cert
  namespace: default   # must be in default so the gateway can use the certificate
spec:
  secretName: tls-cert-secret   # Secret where the certificate will be stored
  dnsNames:
    - argocd.shanana.shop
    - monitor.shanana.shop
  issuerRef:
    name: polom-cl
    kind: ClusterIssuer

