apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-http-route
  namespace: default
spec:
  parentRefs:
    - name: polom-gateway
      sectionName: https   # HTTPS listener
  hostnames:
    - "argocd.shanana.shop"
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      backendRefs:
        - name: argocd-server
          port: 443
          kind: Service
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Proto
                value: "https"
