apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
    - name: polom-gateway
      namespace: default
      sectionName: https  # Use HTTPS listener with TLS termination
  hostnames:
    - "argocd.shanana.shop"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-server
          port: 80   # Use port 80 (HTTP) - the gateway will handle TLS