apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-http-route
  namespace: default
spec:
  parentRefs:
    - name: polom-gateway     # your Gateway
  hostnames:
    - "argocd.shanana.shop"
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      backendRefs:
        - name: argocd-server     # ArgoCD service name
          port: 443
          kind: Service
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              X-Forwarded-Proto: "https"
